services:
  app:
    build: .
    container_name: ripo
    volumes:
      - ./config:/app/config
      - ./db:/app/db
      - ./videos:/app/videos
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
      - PYTHONUNBUFFERED=1
    stdin_open: true
    tty: true
    devices:
      - /dev/video0:/dev/video0
